nlp:
  model_settings:
    spacy_model: "en_core_web_lg"
    bert_model: "bert-base-uncased"
    similarity_threshold: 0.7
  
  processing:
    max_text_length: 10000
    min_skill_confidence: 0.8
  
  scoring:
    skill_weight: 0.6
    experience_weight: 0.3
    education_weight: 0.1